-- ANIMAL_INS / ANIMAL_OUTS
-- 입양 간 기록은 있는데 보호소에 들어온 기록이 없는 동물ID, 이름
-- 동물ID 

SELECT A.ANIMAL_ID, A.NAME
FROM ANIMAL_OUTS A LEFT OUTER JOIN ANIMAL_INS B ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE B.ANIMAL_ID IS NULL
ORDER BY A.ANIMAL_ID