-- ONLINE_SALE / OFFLINE_SALE
-- 2022-03 상품 판매
-- 판매날짜, 상품ID, 유저ID, 판매량
-- 오프라인 USER_ID는 NULL 표기
-- 판매날짜 오름차순, 상품ID 오름차순, 유저ID 오름차순
SELECT  TO_CHAR(A.SALES_DATE, 'YYYY-MM-DD') AS 판매날짜,
        A.PRODUCT_ID AS 상품ID,
        A.USER_ID AS 유저ID,
        A.SALES_AMOUNT AS 판매량
FROM    ONLINE_SALE A 
WHERE   TO_CHAR(A.SALES_DATE, 'YYYY-MM-DD') BETWEEN '2022-03-01' AND '2022-03-31'
UNION ALL
SELECT  TO_CHAR(A.SALES_DATE, 'YYYY-MM-DD') AS 판매날짜,
        A.PRODUCT_ID AS 상품ID,
        NULL AS 유저ID,
        A.SALES_AMOUNT AS 판매량
FROM    OFFLINE_SALE A
WHERE   TO_CHAR(A.SALES_DATE, 'YYYY-MM-DD') BETWEEN '2022-03-01' AND '2022-03-31'
ORDER BY 판매날짜, 상품ID, 유저ID