-- FIRST_HALF / JULY 
-- 7월 아이스크림 총주문량과 산반지 아이스크림 총주문량을 더한 값 상위 3개의 맛 조회

SELECT FLAVOR
FROM (
        SELECT A.FLAVOR, SUM(A.TOTAL_ORDER + B.TOTAL_ORDER) AS TOTAL_ORDER
          FROM FIRST_HALF A INNER JOIN JULY B ON A.FLAVOR = B.FLAVOR
         GROUP BY A.FLAVOR
         ORDER BY TOTAL_ORDER DESC
     )
WHERE ROWNUM < 4
