-- PRODUCT / OFFLINE_SALE 
-- 상품코드별 매출액 합계
--  매출액 내림차순, 상품코드 오름차순

SELECT  A.PRODUCT_CODE, SUM(A.PRICE * SALES_AMOUNT)AS SALES
  FROM  PRODUCT A INNER JOIN OFFLINE_SALE B ON A.PRODUCT_ID = B.PRODUCT_ID
 WHERE  1=1
 GROUP BY PRODUCT_CODE
 ORDER BY SALES DESC, PRODUCT_CODE