-- USED_GOODS_BOARD / USED_GOODS_REPLY
-- 2022년 10월에 작성된 게시글에 대한 댓글
-- 댓글 작성일 오름차순, 게시글 제목 오름차순
SELECT  A.TITLE, 
        A.BOARD_ID, 
        B.REPLY_ID, 
        B.WRITER_ID, 
        B.CONTENTS,
        TO_CHAR(B.CREATED_DATE, 'YYYY-MM-DD') AS CREATED_DATE
  FROM  USED_GOODS_BOARD A INNER JOIN USED_GOODS_REPLY B ON A.BOARD_ID = B.BOARD_ID 
 WHERE TO_CHAR(A.CREATED_DATE, 'YYYY-MM') = '2022-10'
 ORDER BY B.CREATED_DATE, A.TITLE