-- ANIMAL_OUTS
-- 입양 시간대 9:00 - 19:59 입양 건수
-- 시간대별 순서
SELECT TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) AS HOUR,
       COUNT(1) AS COUNT
  FROM ANIMAL_OUTS
 GROUP BY TO_NUMBER(TO_CHAR(DATETIME, 'HH24'))
HAVING TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) BETWEEN 9 AND 19
 ORDER BY HOUR