-- FOOD_WAREHOUSE
-- 경기도에 위치한 창고
-- 냉동시설 여부 NULL = 'N' 대체, 창고ID 오름차순

SELECT  WAREHOUSE_ID, 
        WAREHOUSE_NAME, 
        ADDRESS, 
        NVL(FREEZER_YN, 'N') AS FREEZER_YN
  FROM  FOOD_WAREHOUSE
 WHERE  ADDRESS LIKE '경기도%'
 ORDER BY WAREHOUSE_ID