-- FIRST_HALF / ICECREAM_INFO 
-- 상반기 아이스크림 성분 타입과 총주문량이 작은 순서대로
-- 총주문량 = TOTAL_ORDER


SELECT  B.INGREDIENT_TYPE,
        SUM(A.TOTAL_ORDER) AS TOTAL_ORDER
  FROM  FIRST_HALF A INNER JOIN ICECREAM_INFO B ON A.FLAVOR = B.FLAVOR
 GROUP BY B.INGREDIENT_TYPE
 ORDER BY TOTAL_ORDER