-- BOOK / AUTHOR
-- 카테고리 = '경제'
-- 출판일

SELECT  A.BOOK_ID, B.AUTHOR_NAME, TO_CHAR(A.PUBLISHED_DATE, 'YYYY-MM-DD') AS PUBLISHED_DATE
  FROM  BOOK A INNER JOIN AUTHOR B ON A.AUTHOR_ID = B.AUTHOR_ID
 WHERE  A.CATEGORY = '경제'
 ORDER BY PUBLISHED_DATE 