-- CAR_RENTAL_COMPANY_CAR
-- 자동차 종류가 'SUV'의 평균 일일 대여 요금
-- 평균 대여 요금은 소수점 첫번째 자리에서 반올림
-- 칼럼명 : AVERAGE_FEE
SELECT ROUND(AVG(DAILY_FEE), 0) AS AVERAGE_FEE
  FROM CAR_RENTAL_COMPANY_CAR
 WHERE CAR_TYPE = 'SUV'