-- MEMBER_PROFILE
-- 생일이 3월인 여성 회원
-- 전화번호 NULL인 경우 제외
-- 회원ID 오름차순
SELECT  MEMBER_ID, 
        MEMBER_NAME,
        GENDER,
        TO_CHAR(DATE_OF_BIRTH, 'YYYY-MM-DD') AS DATE_OF_BIRTH
  FROM  MEMBER_PROFILE
 WHERE  GENDER = 'W' AND TO_CHAR(DATE_OF_BIRTH, 'MM') = '03' AND TLNO IS NOT NULL
 ORDER BY MEMBER_ID